module.exports = function(sequelize, DataTypes) {
  var Store = sequelize.define("Store", {
    store_name: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: {
        len: [1]
      }
    },
    store_city: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: {
        len: [1]
      }
    },
    store_state: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: {
        len: [1]
      }
    }
  },
  {
    timestamps: false // prevent autogenerated timestamp attributes (updatedAt, createdAt)
  }
);
  return Store;
};
